### PR TITLE
Initial BoltDB support for #48.

### PR DESCRIPTION
**Pull request by fluffle**
# Initial BoltDB support for #48.
- Introduces a set of interfaces for DB access: `Database`, `Collection` and `Key`.
- Provides MongoDB and BoltDB implementations for `Database` and `Collection`.
- Only enough done to allow migration of config collection.
- Starts mapping MongoDB data model into BoltDB:
  - MongoDB "Collection" == BoltDB "Bucket".
  - `Key` is represented by an ordered list of string key:value tuples.
    - MongoDB reads/writes turn these into `bson.M{key: value, ...}` for Find/Upsert.
    - BoltDB reads/writes turn these into `[]byte{key + "\x1f" + value}` nested bucket keys for Get/Put.
- Migration triggered manually via notice, logs any diffs as errors.
- Stolen patience diff algorithm from Bram Cohen \o/

[Review on Reviewable](https://reviewable.io/reviews/fluffle/sp0rkle/62)

### CODE REVIEW

**Comment by bob-smith** [comment]
I don't know mongo, nor boltdb

None core bits look ok (documentation and .travis are inline)

Need to do backups

---

Review status: 0 of 24 files reviewed at latest revision, 1 unresolved discussion.

---

*[main.go, line 36 \[r1\]](https://reviewable.io:443/reviews/fluffle/sp0rkle/62#-KBA6WJpuv0jihDXlLYp:-KBA6WJqvSA_yqWvyjpr:1422629840) ([raw file](https://github.com/fluffle/sp0rkle/blob/9f2f0f0bde5a15275e2cc7572a4916196e5aa8db/main.go#L36)):*
New boltdb needs adding to backup.sh

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fluffle/sp0rkle/62#-:-KBA6-r4r_9-sjN9pXlw:-2106510542)*

**Comment by fluffle** [comment]
Oh, backups are an excellent point. Bolt maintains a lock on the db while sp0rkle is running so it's not possible to write an external tool to back up the DB. Their suggested approach is to simply write out a copy of the db from a transaction:

https://github.com/boltdb/bolt#database-backups

I should be able to do this relatively easily using a poller. It's also an incentive to fix some of the poller problems at some point, so they can be stopped/started manually if necessary.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fluffle/sp0rkle/62#-:-KBAAr-9Hocz7xL0O-fW:-2027040358)*

**Comment by bob-smith** [comment]
Review status: 0 of 24 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 37 \[r2\]](https://reviewable.io:443/reviews/fluffle/sp0rkle/62#-KBIz7zkXqely8Chqqt6:-KBIz7zkXqely8Chqqt7:-1251393021) ([raw file](https://github.com/fluffle/sp0rkle/blob/c4b94705bd6ab826a7104717643b486182c187e5/README.md#L37)):*
Is this note worthy?

Also maybe it should be rewritten as:
# boltdb includes the 'bolt' cmdline 

In case the order changes

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fluffle/sp0rkle/62)*

**Comment by fluffle** [comment]
Gonna merge this with master now the migration stuff is looking a bit less shonky.

Next up: stats package and figuring out how to abuse bolt buckets for indexes \o/

---

Review status: 0 of 25 files reviewed at latest revision, 2 unresolved discussions.

---

*[main.go, line 36 \[r1\]](https://reviewable.io:443/reviews/fluffle/sp0rkle/62#-KBA6WJpuv0jihDXlLYp:-KC7uFwUCdseTbuUXI3h:-499146009) ([raw file](https://github.com/fluffle/sp0rkle/blob/9f2f0f0bde5a15275e2cc7572a4916196e5aa8db/main.go#L36)):*
Done.

---

*[README.md, line 37 \[r2\]](https://reviewable.io:443/reviews/fluffle/sp0rkle/62#-KBIz7zkXqely8Chqqt6:-KC7ypUgj-n2__aL0q2Z:-499146009) ([raw file](https://github.com/fluffle/sp0rkle/blob/c4b94705bd6ab826a7104717643b486182c187e5/README.md#L37)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fluffle/sp0rkle/62#-:-KC830zyKEz04Imbgwlc:185012146)*

**Comment by bob-smith** [comment]
Review status: 0 of 25 files reviewed at latest revision, 3 unresolved discussions.

---

*[.travis.yml, line 22 \[r6\]](https://reviewable.io:443/reviews/fluffle/sp0rkle/62#-KCB4xE2KAurAo5Zzrha:-KCB4xE3Sur2S1j7X8yR:1006440590) ([raw file](https://github.com/fluffle/sp0rkle/blob/d3f8add11eb207da133d3132f596364ea9b8069e/.travis.yml#L22)):*
Should this be

    go get github.com/boltdb/bolt/...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fluffle/sp0rkle/62)*

**Comment by fluffle** [comment]
Nah, the bolt tool is only vaguely useful for manual debugging, it's not
used in the code anywhere...

**Comment by bob-smith** [comment]
Reviewed 13 of 24 files at r1, 1 of 4 files at r3, 8 of 9 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/fluffle/sp0rkle/62)*

**Pull request merged**
